/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project3pemvis;

/**
 *
 * @author firak
 */
public class perpustakaan extends javax.swing.JFrame {
    
    
    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgdaftar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rblaut = new javax.swing.JRadioButton();
        rbhujan = new javax.swing.JRadioButton();
        rbfilosofi = new javax.swing.JRadioButton();
        rbpulang = new javax.swing.JRadioButton();
        rbpp = new javax.swing.JRadioButton();
        rbpergi = new javax.swing.JRadioButton();
        rbnegeri = new javax.swing.JRadioButton();
        rblima = new javax.swing.JRadioButton();
        rbseni = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textinformasi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN TELANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DAFTAR BUKU");

        bgdaftar.add(rblaut);
        rblaut.setText("Laut Bercerita");
        rblaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblautActionPerformed(evt);
            }
        });

        bgdaftar.add(rbhujan);
        rbhujan.setText("Hujan");
        rbhujan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbhujanActionPerformed(evt);
            }
        });

        bgdaftar.add(rbfilosofi);
        rbfilosofi.setText("Filosofi Teras");
        rbfilosofi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfilosofiActionPerformed(evt);
            }
        });

        bgdaftar.add(rbpulang);
        rbpulang.setText("Pulang");
        rbpulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpulangActionPerformed(evt);
            }
        });

        bgdaftar.add(rbpp);
        rbpp.setText("Pulang-Pergi");
        rbpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbppActionPerformed(evt);
            }
        });

        bgdaftar.add(rbpergi);
        rbpergi.setText("Pergi");
        rbpergi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpergiActionPerformed(evt);
            }
        });

        bgdaftar.add(rbnegeri);
        rbnegeri.setText("Negeri Para Bedebah");
        rbnegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnegeriActionPerformed(evt);
            }
        });

        bgdaftar.add(rblima);
        rblima.setText("Lima Cerita");
        rblima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblimaActionPerformed(evt);
            }
        });

        bgdaftar.add(rbseni);
        rbseni.setText("Seni Hidup Minimalis");
        rbseni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbseniActionPerformed(evt);
            }
        });

        textinformasi.setColumns(20);
        textinformasi.setRows(5);
        jScrollPane1.setViewportView(textinformasi);

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setText("INFORMASI BUKU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbhujan)
                    .addComponent(rblaut)
                    .addComponent(rbfilosofi))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbpulang)
                            .addComponent(rbpp)
                            .addComponent(rbpergi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbseni)
                            .addComponent(rbnegeri)
                            .addComponent(rblima))
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblaut)
                    .addComponent(rbpulang)
                    .addComponent(rbnegeri))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbhujan)
                    .addComponent(rbpp)
                    .addComponent(rblima))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfilosofi)
                    .addComponent(rbpergi)
                    .addComponent(rbseni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rblautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblautActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Laut Bercerita\n Penulis : Leila S. Chudori\n Penerbit : KPG (Kepustakaan Populer Gramedia)\n Tahun Terbit : 2017\n Tebal Buku : 379 Halaman");
    }//GEN-LAST:event_rblautActionPerformed

    private void rbhujanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbhujanActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Hujan\n Penulis : Tere Liye\n Penerbit : Gramedia Pustaka Utama\n Tahun Terbit : 2016\n Tebal Buku : 320 Halaman");
    }//GEN-LAST:event_rbhujanActionPerformed

    private void rbfilosofiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfilosofiActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Filosofi Teras\n Penulis : Henry Manampiring\n Penerbit : PT Kompas Media Nusantara\n Tahun Terbit : 2018\n Tebal Buku : 344 Halaman");
    }//GEN-LAST:event_rbfilosofiActionPerformed

    private void rbpulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpulangActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Pulang\n Penulis : Tere Liye\n Penerbit : Republika Penerbit\n Tahun Terbit : 2015\n Tebal Buku : 400 Halaman");
    }//GEN-LAST:event_rbpulangActionPerformed

    private void rbppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbppActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Pulang-Pergi\n Penulis : Tere Liye\n Penerbit : PT Sabak Grip Nusantara\n Tahun Terbit : 2021\n Tebal Buku : 417 Halaman");
    }//GEN-LAST:event_rbppActionPerformed

    private void rbpergiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpergiActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Pergi\n Penulis : Tere Liye\n Penerbit : Republika Penerbit\n Tahun Terbit : 2018\n Tebal Buku : 460 Halaman");
    }//GEN-LAST:event_rbpergiActionPerformed

    private void rbnegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnegeriActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Negeri Para Bedebah\n Penulis : Tere Liye\n Penerbit : Gramedia Pustaka Utama\n Tahun Terbit : 2012\n Tebal Buku : 440 Halaman");
    }//GEN-LAST:event_rbnegeriActionPerformed

    private void rblimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblimaActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Lima Cerita\n Penulis : Desi Anwar\n Penerbit : Gramedia Pustaka Utama\n Tahun Terbit : 2019\n Tebal Buku : 316 Halaman");
    }//GEN-LAST:event_rblimaActionPerformed

    private void rbseniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbseniActionPerformed
        // TODO add your handling code here:
        textinformasi.setText(" Judul Buku : Seni Hidup Minimalis:\n Petunjuk Minimalis Menuju Hidup yang Apik, Tertata, dan Sederhana\n Penulis : Francine Jay\n Penerbit : Gramedia Pustaka Utama\n Tahun Terbit : 2019\n Tebal Buku : 263 Halaman");
    }//GEN-LAST:event_rbseniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgdaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbfilosofi;
    private javax.swing.JRadioButton rbhujan;
    private javax.swing.JRadioButton rblaut;
    private javax.swing.JRadioButton rblima;
    private javax.swing.JRadioButton rbnegeri;
    private javax.swing.JRadioButton rbpergi;
    private javax.swing.JRadioButton rbpp;
    private javax.swing.JRadioButton rbpulang;
    private javax.swing.JRadioButton rbseni;
    private javax.swing.JTextArea textinformasi;
    // End of variables declaration//GEN-END:variables
}
